using AuthenticationApi.IRepositories;
using AuthenticationApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;



namespace AuthenticationApi.DbContexts
{
    public class UnitOfContextImp : IUnitOfContext
    {
        private readonly TempaAuthContext _dbContext;
        public UnitOfContextImp(TempaAuthContext dbContext)
        {
            _dbContext = dbContext;
        }
        public async Task<int> SaveTrans()
        {
            try
            {
                using (var transaction = _dbContext.Database.BeginTransaction())
                {
                    try
                    {
                        int save = await _dbContext.SaveChangesAsync();
                        transaction.Commit();

                        return save;
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                        return -1;
                    }
                }
            }
            catch(Exception ex)
            {
                return -1;
            }
        }

        public async Task<int> Save()
        {
            try
            {
                int save = await _dbContext.SaveChangesAsync();
                

                return save;
            }
            catch (Exception ex)
            {
                return -1;
            }
        }
        public async Task<int> SaveAuditTrail(string EmailOrUserid)
        {
            int saved = -1;
            try
            {
                foreach (var entry in _dbContext.ChangeTracker.Entries().ToList()
                .Where(e => e.State == EntityState.Added || e.State == EntityState.Modified || e.State == EntityState.Deleted))
                {

                    AuditEntry auditEntry = new AuditEntry(entry);

                    var oldValues = await entry.GetDatabaseValuesAsync().ConfigureAwait(false);

                    foreach (var property in entry.Properties.ToList())
                    {
                        if (property.IsTemporary)
                        {
                            // value will be generated by the database, get the value after saving
                            //auditEntry.TemporaryProperties.Add(property);
                            continue;
                        }

                        string propertyName = property.Metadata.Name;
                        if (property.Metadata.IsPrimaryKey())
                        {
                            auditEntry.KeyValues[propertyName] = property.CurrentValue;
                            continue;
                        }

                        switch (entry.State)
                        {
                            case EntityState.Added:
                                auditEntry.NewValues[propertyName] = property.CurrentValue;
                                break;

                            case EntityState.Deleted:
                                //auditEntry.OldValues[propertyName] = property.OriginalValue;
                                auditEntry.OldValues[propertyName] = oldValues[propertyName];
                                break;

                            case EntityState.Modified:
                                if (property.IsModified)
                                {
                                    //auditEntry.OldValues[propertyName] = property.OriginalValue;
                                    auditEntry.OldValues[propertyName] = oldValues[propertyName];
                                    auditEntry.NewValues[propertyName] = property.CurrentValue;
                                    auditEntry.columnName = propertyName;
                                }
                                break;
                        }
                    }
                    if (entry.State == EntityState.Added)
                    {
                    }
                    if (entry.State == EntityState.Modified)
                    {

                        object[] ObjectId = entry.Metadata.FindPrimaryKey()
                            .Properties
                            .Select(p => entry.Property(p.Name).CurrentValue)
                            .ToArray();

                        AuditTrail audit = new AuditTrail();

                        audit.Eventdateutc = DateTime.Now;
                        audit.Tablename = entry.Metadata.GetDefaultTableName();// entry.Metadata.Relational().TableName;
                        audit.Originalvalue = auditEntry.OldValues.Count == 0 ? null : JsonConvert.SerializeObject(auditEntry.OldValues);
                        audit.Newvalue = auditEntry.NewValues.Count == 0 ? null : JsonConvert.SerializeObject(auditEntry.NewValues);
                        audit.Eventtype = "M";// entry.Property("Status").CurrentValue.ToString();
                        audit.Recordid = ObjectId == null ? "" : ObjectId[0].ToString();
                        audit.EmailOrUserid = EmailOrUserid;
                        // audit.columnname =  auditEntry.columnName;
                        await _dbContext.AuditTrail.AddAsync(audit);
                    }
                    if (entry.State == EntityState.Deleted)
                    {

                        object[] ObjectId = entry.Metadata.FindPrimaryKey()
                            .Properties
                            .Select(p => entry.Property(p.Name).CurrentValue)
                            .ToArray();

                        AuditTrail audit = new AuditTrail();

                        audit.Eventdateutc = DateTime.Now;
                        audit.Tablename = entry.Metadata.GetDefaultTableName();//.().TableName;
                        audit.Originalvalue = auditEntry.OldValues.Count == 0 ? null : JsonConvert.SerializeObject(auditEntry.OldValues);
                        audit.Newvalue = auditEntry.NewValues.Count == 0 ? null : JsonConvert.SerializeObject(auditEntry.NewValues);
                        audit.Eventtype = "D";// entry.Property("Status").CurrentValue.ToString();
                        audit.Recordid = ObjectId == null ? "" : ObjectId[0].ToString();
                        audit.EmailOrUserid = EmailOrUserid;
                        // audit.columnname =  auditEntry.columnName;
                        await _dbContext.AuditTrail.AddAsync(audit);
                    }
                }
                saved = await _dbContext.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                var exM = ex == null ? ex.InnerException.Message : ex.Message;

            }
            return saved;
        }

    }


    public class AuditEntry
    {
        public AuditEntry(EntityEntry entry)
        {
            Entry = entry;
        }
        public EntityEntry Entry { get; }
        public string TableName { get; set; }
        public string columnName { get; set; }
        public Dictionary<string, object> KeyValues { get; } = new Dictionary<string, object>();
        public Dictionary<string, object> OldValues { get; } = new Dictionary<string, object>();
        public Dictionary<string, object> NewValues { get; } = new Dictionary<string, object>();
        public List<PropertyEntry> TemporaryProperties { get; } = new List<PropertyEntry>();
        public bool HasTemporaryProperties => TemporaryProperties.Any();
    }


}


public class AuditEntry
{
    public AuditEntry(EntityEntry entry)
    {
        Entry = entry;
    }
    public EntityEntry Entry { get; }
    public string TableName { get; set; }
    public string columnName { get; set; }
    public Dictionary<string, object> KeyValues { get; } = new Dictionary<string, object>();
    public Dictionary<string, object> OldValues { get; } = new Dictionary<string, object>();
    public Dictionary<string, object> NewValues { get; } = new Dictionary<string, object>();
    public List<PropertyEntry> TemporaryProperties { get; } = new List<PropertyEntry>();
    public bool HasTemporaryProperties => TemporaryProperties.Any();
}
